// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProcessInstanceDTO } from './ProcessInstanceDTO';
import {
  ProcessInstanceDTOFromJSON,
  ProcessInstanceDTOFromJSONTyped,
  ProcessInstanceDTOToJSON,
} from './ProcessInstanceDTO';

/**
 *
 * @export
 * @interface AssessedProcessInstanceDTO
 */
export interface AssessedProcessInstanceDTO {
  /**
   *
   * @type {ProcessInstanceDTO}
   * @memberof AssessedProcessInstanceDTO
   */
  instance: ProcessInstanceDTO;
  /**
   *
   * @type {ProcessInstanceDTO}
   * @memberof AssessedProcessInstanceDTO
   */
  assessedBy?: ProcessInstanceDTO;
}

/**
 * Check if a given object implements the AssessedProcessInstanceDTO interface.
 */
export function instanceOfAssessedProcessInstanceDTO(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'instance' in value;

  return isInstance;
}

export function AssessedProcessInstanceDTOFromJSON(
  json: any,
): AssessedProcessInstanceDTO {
  return AssessedProcessInstanceDTOFromJSONTyped(json, false);
}

export function AssessedProcessInstanceDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssessedProcessInstanceDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    instance: ProcessInstanceDTOFromJSON(json['instance']),
    assessedBy: !exists(json, 'assessedBy')
      ? undefined
      : ProcessInstanceDTOFromJSON(json['assessedBy']),
  };
}

export function AssessedProcessInstanceDTOToJSON(
  value?: AssessedProcessInstanceDTO | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    instance: ProcessInstanceDTOToJSON(value.instance),
    assessedBy: ProcessInstanceDTOToJSON(value.assessedBy),
  };
}
