// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WorkflowDTO } from './WorkflowDTO';
import {
  WorkflowDTOFromJSON,
  WorkflowDTOFromJSONTyped,
  WorkflowDTOToJSON,
} from './WorkflowDTO';

/**
 *
 * @export
 * @interface CreateWorkflow201Response
 */
export interface CreateWorkflow201Response {
  /**
   *
   * @type {WorkflowDTO}
   * @memberof CreateWorkflow201Response
   */
  workflowItem?: WorkflowDTO;
}

/**
 * Check if a given object implements the CreateWorkflow201Response interface.
 */
export function instanceOfCreateWorkflow201Response(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CreateWorkflow201ResponseFromJSON(
  json: any,
): CreateWorkflow201Response {
  return CreateWorkflow201ResponseFromJSONTyped(json, false);
}

export function CreateWorkflow201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWorkflow201Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    workflowItem: !exists(json, 'workflowItem')
      ? undefined
      : WorkflowDTOFromJSON(json['workflowItem']),
  };
}

export function CreateWorkflow201ResponseToJSON(
  value?: CreateWorkflow201Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    workflowItem: WorkflowDTOToJSON(value.workflowItem),
  };
}
