// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 *
 * @export
 * @interface CreateWorkflowRequest
 */
export interface CreateWorkflowRequest {
  /**
   *
   * @type {string}
   * @memberof CreateWorkflowRequest
   */
  uri: string;
  /**
   *
   * @type {string}
   * @memberof CreateWorkflowRequest
   */
  body?: string;
}

/**
 * Check if a given object implements the CreateWorkflowRequest interface.
 */
export function instanceOfCreateWorkflowRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'uri' in value;

  return isInstance;
}

export function CreateWorkflowRequestFromJSON(
  json: any,
): CreateWorkflowRequest {
  return CreateWorkflowRequestFromJSONTyped(json, false);
}

export function CreateWorkflowRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWorkflowRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uri: json['uri'],
    body: !exists(json, 'body') ? undefined : json['body'],
  };
}

export function CreateWorkflowRequestToJSON(
  value?: CreateWorkflowRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uri: value.uri,
    body: value.body,
  };
}
