// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 *
 * @export
 * @interface ExecuteWorkflowRequestDTO
 */
export interface ExecuteWorkflowRequestDTO {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ExecuteWorkflowRequestDTO
   */
  inputData: { [key: string]: string };
}

/**
 * Check if a given object implements the ExecuteWorkflowRequestDTO interface.
 */
export function instanceOfExecuteWorkflowRequestDTO(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'inputData' in value;

  return isInstance;
}

export function ExecuteWorkflowRequestDTOFromJSON(
  json: any,
): ExecuteWorkflowRequestDTO {
  return ExecuteWorkflowRequestDTOFromJSONTyped(json, false);
}

export function ExecuteWorkflowRequestDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExecuteWorkflowRequestDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    inputData: json['inputData'],
  };
}

export function ExecuteWorkflowRequestDTOToJSON(
  value?: ExecuteWorkflowRequestDTO | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    inputData: value.inputData,
  };
}
