// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 *
 * @export
 * @interface PaginationInfoDTO
 */
export interface PaginationInfoDTO {
  /**
   *
   * @type {number}
   * @memberof PaginationInfoDTO
   */
  limit?: number;
  /**
   *
   * @type {number}
   * @memberof PaginationInfoDTO
   */
  offset?: number;
  /**
   *
   * @type {number}
   * @memberof PaginationInfoDTO
   */
  totalCount?: number;
}

/**
 * Check if a given object implements the PaginationInfoDTO interface.
 */
export function instanceOfPaginationInfoDTO(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PaginationInfoDTOFromJSON(json: any): PaginationInfoDTO {
  return PaginationInfoDTOFromJSONTyped(json, false);
}

export function PaginationInfoDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginationInfoDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    limit: !exists(json, 'limit') ? undefined : json['limit'],
    offset: !exists(json, 'offset') ? undefined : json['offset'],
    totalCount: !exists(json, 'totalCount') ? undefined : json['totalCount'],
  };
}

export function PaginationInfoDTOToJSON(value?: PaginationInfoDTO | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    limit: value.limit,
    offset: value.offset,
    totalCount: value.totalCount,
  };
}
