// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 *
 * @export
 * @interface ProcessInstanceErrorDTO
 */
export interface ProcessInstanceErrorDTO {
  /**
   * Type name
   * @type {string}
   * @memberof ProcessInstanceErrorDTO
   */
  typename?: string;
  /**
   * Node definition ID
   * @type {string}
   * @memberof ProcessInstanceErrorDTO
   */
  nodeDefinitionId?: string;
  /**
   * Error message (optional)
   * @type {string}
   * @memberof ProcessInstanceErrorDTO
   */
  message?: string;
}

/**
 * Check if a given object implements the ProcessInstanceErrorDTO interface.
 */
export function instanceOfProcessInstanceErrorDTO(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ProcessInstanceErrorDTOFromJSON(
  json: any,
): ProcessInstanceErrorDTO {
  return ProcessInstanceErrorDTOFromJSONTyped(json, false);
}

export function ProcessInstanceErrorDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProcessInstanceErrorDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    typename: !exists(json, '__typename') ? undefined : json['__typename'],
    nodeDefinitionId: !exists(json, 'nodeDefinitionId')
      ? undefined
      : json['nodeDefinitionId'],
    message: !exists(json, 'message') ? undefined : json['message'],
  };
}

export function ProcessInstanceErrorDTOToJSON(
  value?: ProcessInstanceErrorDTO | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    __typename: value.typename,
    nodeDefinitionId: value.nodeDefinitionId,
    message: value.message,
  };
}
