// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Status of the workflow run
 * @export
 */
export const ProcessInstanceStatusDTO = {
  Running: 'Running',
  Error: 'Error',
  Completed: 'Completed',
  Aborted: 'Aborted',
  Suspended: 'Suspended',
} as const;
export type ProcessInstanceStatusDTO =
  (typeof ProcessInstanceStatusDTO)[keyof typeof ProcessInstanceStatusDTO];

export function ProcessInstanceStatusDTOFromJSON(
  json: any,
): ProcessInstanceStatusDTO {
  return ProcessInstanceStatusDTOFromJSONTyped(json, false);
}

export function ProcessInstanceStatusDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProcessInstanceStatusDTO {
  return json as ProcessInstanceStatusDTO;
}

export function ProcessInstanceStatusDTOToJSON(
  value?: ProcessInstanceStatusDTO | null,
): any {
  return value as any;
}
