// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 *
 * @export
 * @interface WorkflowRunStatusDTO
 */
export interface WorkflowRunStatusDTO {
  /**
   *
   * @type {string}
   * @memberof WorkflowRunStatusDTO
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof WorkflowRunStatusDTO
   */
  value?: string;
}

/**
 * Check if a given object implements the WorkflowRunStatusDTO interface.
 */
export function instanceOfWorkflowRunStatusDTO(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function WorkflowRunStatusDTOFromJSON(json: any): WorkflowRunStatusDTO {
  return WorkflowRunStatusDTOFromJSONTyped(json, false);
}

export function WorkflowRunStatusDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkflowRunStatusDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    key: !exists(json, 'key') ? undefined : json['key'],
    value: !exists(json, 'value') ? undefined : json['value'],
  };
}

export function WorkflowRunStatusDTOToJSON(
  value?: WorkflowRunStatusDTO | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    key: value.key,
    value: value.value,
  };
}
