// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationInfoDTO } from './PaginationInfoDTO';
import {
  PaginationInfoDTOFromJSON,
  PaginationInfoDTOFromJSONTyped,
  PaginationInfoDTOToJSON,
} from './PaginationInfoDTO';
import type { WorkflowOverviewDTO } from './WorkflowOverviewDTO';
import {
  WorkflowOverviewDTOFromJSON,
  WorkflowOverviewDTOFromJSONTyped,
  WorkflowOverviewDTOToJSON,
} from './WorkflowOverviewDTO';

/**
 *
 * @export
 * @interface WorkflowOverviewListResultDTO
 */
export interface WorkflowOverviewListResultDTO {
  /**
   *
   * @type {Array<WorkflowOverviewDTO>}
   * @memberof WorkflowOverviewListResultDTO
   */
  overviews?: Array<WorkflowOverviewDTO>;
  /**
   *
   * @type {PaginationInfoDTO}
   * @memberof WorkflowOverviewListResultDTO
   */
  paginationInfo?: PaginationInfoDTO;
}

/**
 * Check if a given object implements the WorkflowOverviewListResultDTO interface.
 */
export function instanceOfWorkflowOverviewListResultDTO(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function WorkflowOverviewListResultDTOFromJSON(
  json: any,
): WorkflowOverviewListResultDTO {
  return WorkflowOverviewListResultDTOFromJSONTyped(json, false);
}

export function WorkflowOverviewListResultDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkflowOverviewListResultDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    overviews: !exists(json, 'overviews')
      ? undefined
      : (json['overviews'] as Array<any>).map(WorkflowOverviewDTOFromJSON),
    paginationInfo: !exists(json, 'paginationInfo')
      ? undefined
      : PaginationInfoDTOFromJSON(json['paginationInfo']),
  };
}

export function WorkflowOverviewListResultDTOToJSON(
  value?: WorkflowOverviewListResultDTO | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    overviews:
      value.overviews === undefined
        ? undefined
        : (value.overviews as Array<any>).map(WorkflowOverviewDTOToJSON),
    paginationInfo: PaginationInfoDTOToJSON(value.paginationInfo),
  };
}
