// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WorkflowSuggestionDTO } from './WorkflowSuggestionDTO';
import {
  WorkflowSuggestionDTOFromJSON,
  WorkflowSuggestionDTOFromJSONTyped,
  WorkflowSuggestionDTOToJSON,
} from './WorkflowSuggestionDTO';

/**
 *
 * @export
 * @interface WorkflowDataDTO
 */
export interface WorkflowDataDTO {
  /**
   *
   * @type {Array<Array<WorkflowSuggestionDTO>>}
   * @memberof WorkflowDataDTO
   */
  workflowoptions?: Array<Array<WorkflowSuggestionDTO>>;
}

/**
 * Check if a given object implements the WorkflowDataDTO interface.
 */
export function instanceOfWorkflowDataDTO(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function WorkflowDataDTOFromJSON(json: any): WorkflowDataDTO {
  return WorkflowDataDTOFromJSONTyped(json, false);
}

export function WorkflowDataDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkflowDataDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    workflowoptions: !exists(json, 'workflowoptions')
      ? undefined
      : json['workflowoptions'],
  };
}

export function WorkflowDataDTOToJSON(value?: WorkflowDataDTO | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    workflowoptions: value.workflowoptions,
  };
}
