// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Orchestrator plugin
 * API to interact with orchestrator plugin
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 *
 * @export
 * @interface WorkflowSpecFileDTO
 */
export interface WorkflowSpecFileDTO {
  /**
   *
   * @type {string}
   * @memberof WorkflowSpecFileDTO
   */
  path?: string;
  /**
   * JSON string
   * @type {string}
   * @memberof WorkflowSpecFileDTO
   */
  content: string;
}

/**
 * Check if a given object implements the WorkflowSpecFileDTO interface.
 */
export function instanceOfWorkflowSpecFileDTO(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'content' in value;

  return isInstance;
}

export function WorkflowSpecFileDTOFromJSON(json: any): WorkflowSpecFileDTO {
  return WorkflowSpecFileDTOFromJSONTyped(json, false);
}

export function WorkflowSpecFileDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkflowSpecFileDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    path: !exists(json, 'path') ? undefined : json['path'],
    content: json['content'],
  };
}

export function WorkflowSpecFileDTOToJSON(
  value?: WorkflowSpecFileDTO | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    path: value.path,
    content: value.content,
  };
}
