proxy:
  '/parodos':
    target: 'http://localhost:8080/api/v1'
    changeOrigin: true
    redirect: follow
    cache: 'no-cache'
    headers:
      Content-Type: 'application/json'
      accept: 'application/json'
      Authorization: ${PARODOS_AUTH_KEY}