apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: janus-idp-backstage-plugins
  description: An example of a Backstage application.
spec:
  type: website
  owner: group:janus-idp
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: janus-idp-backstage-plugins
spec:
  targets:
    - ./plugins/**/catalog-info.yaml
    - ./utils/**/catalog-info.yaml
