# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rhdh
spec:
  owner: rhdh-team
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: janus-idp-backstage-plugins
  title: RHDH plugins
  description: Backstage Plugins by Red Hat
  annotations:
    backstage.io/source-location: url:https://github.com/janus-idp/backstage-plugins/tree/main
    backstage.io/view-url: https://github.com/janus-idp/backstage-plugins/blob/main/catalog-info.yaml
    backstage.io/edit-url: https://github.com/janus-idp/backstage-plugins/edit/main/catalog-info.yaml
    github.com/project-slug: janus-idp/backstage-plugins
    github.com/team-slug: janus-idp/maintainers-plugins
    sonarqube.org/project-key: janus-idp_backstage-plugins
  links:
    - url: https://github.com/janus-idp/backstage-plugins/tree/main
      title: GitHub Source
      icon: source
      type: source
spec:
  type: website
  lifecycle: production
  owner: rhdh-team
  system: rhdh
---
# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-location
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: janus-idp-backstage-plugins
spec:
  targets:
    - ./plugins/aap-backend/catalog-info.yaml
    - ./plugins/audit-log-node/catalog-info.yaml
    - ./plugins/shared-react/catalog-info.yaml
    - ./plugins/web-terminal/catalog-info.yaml
    - ./packages/cli/catalog-info.yaml
