apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jdoe
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [jdoe, jdoe-2]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jdoe-2
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [jdoe]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: jdoe
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: jdoe
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [jdoe]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: jdoe-2
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: jdoe
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [jdoe]
