/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v2/workflows/overview': {
    /** @description Get a list of workflow overviews */
    get: operations['getWorkflowsOverview'];
  };
  '/v2/workflows/{workflowId}/overview': {
    /** @description Get a workflow overview by ID */
    get: operations['getWorkflowOverviewById'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    WorkflowOverviewListResultDTO: {
      overviews?: components['schemas']['WorkflowOverviewDTO'][];
      paginationInfo?: components['schemas']['PaginationInfoDTO'];
    };
    WorkflowOverviewDTO: {
      /** @description Workflow unique identifier */
      workflowId?: string;
      /** @description Workflow name */
      name?: string;
      uri?: string;
      lastTriggeredMs?: number;
      lastRunStatus?: string;
      type?: string;
      avgDurationMs?: number;
      description?: string;
    };
    PaginationInfoDTO: {
      limit?: number;
      offset?: number;
      totalCount?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** @description Get a list of workflow overviews */
  getWorkflowsOverview: {
    responses: {
      /** @description Success */
      200: {
        content: {
          'application/json': components['schemas']['WorkflowOverviewListResultDTO'];
        };
      };
      /** @description Error fetching workflow overviews */
      500: {
        content: {
          'application/json': {
            /** @description Error message */
            message?: string;
          };
        };
      };
    };
  };
  /** @description Get a workflow overview by ID */
  getWorkflowOverviewById: {
    parameters: {
      path: {
        /** @description Unique identifier of the workflow */
        workflowId: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          'application/json': components['schemas']['WorkflowOverview'];
        };
      };
      /** @description Error fetching workflow overview */
      500: {
        content: {
          'application/json': {
            /** @description Error message */
            message?: string;
          };
        };
      };
    };
  };
}
