export const groups = [
  {
    id: '9cf51b5d-e066-4ed8-940c-dc6da77f81a5',
    name: 'biggroup',
    path: '/biggroup',
    subGroupCount: 1,
    subGroups: [],
    access: {
      view: true,
      viewMembers: true,
      manageMembers: false,
      manage: false,
      manageMembership: false,
    },
  },
  {
    id: 'eefa5b46-0509-41d8-b8b3-7ddae9c83632',
    name: 'subgroup',
    path: '/biggroup/subgroup',
    parentId: '9cf51b5d-e066-4ed8-940c-dc6da77f81a5',
    subGroupCount: 0,
    subGroups: [],
    access: {
      view: true,
      viewMembers: true,
      manageMembers: false,
      manage: false,
      manageMembership: false,
    },
  },
  {
    id: '557501bd-8188-41c0-a2d5-43ff3d5b0258',
    name: 'emptygroup',
    path: '/emptygroup',
    subGroupCount: 0,
    subGroups: [],
    access: {
      view: true,
      viewMembers: true,
      manageMembers: false,
      manage: false,
      manageMembership: false,
    },
  },
];

export const topLevelGroups = [
  {
    id: '9cf51b5d-e066-4ed8-940c-dc6da77f81a5',
    name: 'biggroup',
    path: '/biggroup',
    subGroupCount: 1,
    subGroups: [],
    access: {
      view: true,
      viewMembers: true,
      manageMembers: false,
      manage: false,
      manageMembership: false,
    },
  },
  {
    id: '557501bd-8188-41c0-a2d5-43ff3d5b0258',
    name: 'emptygroup',
    path: '/emptygroup',
    subGroupCount: 0,
    subGroups: [],
    access: {
      view: true,
      viewMembers: true,
      manageMembers: false,
      manage: false,
      manageMembership: false,
    },
  },
];

export const users = [
  {
    id: '59efec15-a00b-4700-8833-5f4cdecc1132',
    createdTimestamp: 1686170983010,
    username: 'jamesdoe',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: '',
    lastName: '',
    email: 'jamesdoe@gmail.com',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: false,
      view: true,
      mapRoles: false,
      impersonate: false,
      manage: false,
    },
  },
  {
    id: 'c982b51a-abf6-4f68-bfdf-a1c6257214fc',
    createdTimestamp: 1686170953553,
    username: 'joedoe',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: '',
    lastName: '',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: false,
      view: true,
      mapRoles: false,
      impersonate: false,
      manage: false,
    },
  },
  {
    id: '2bf97dbd-fd6a-47ae-986b-2632fa95e03f',
    createdTimestamp: 1686170890908,
    username: 'johndoe',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'John',
    lastName: 'Doe',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: false,
      view: true,
      mapRoles: false,
      impersonate: false,
      manage: false,
    },
  },
];

export const groupMembers = [
  ['jamesdoe'],
  [],
  [],
  ['jamesdoe', 'joedoe', 'johndoe'],
];

export const subgroups = [
  [
    {
      id: 'd6eea811-2324-44b4-a272-c7a080e6f26c',
      name: 'test-nested-gp-1',
      path: '/test-group-1/test-nested-gp-1',
      parentId: 'fa8eef02-0cea-42a8-937f-e1046e05c241',
      subGroupCount: 0,
      subGroups: [],
      access: {
        view: true,
        viewMembers: true,
        manageMembers: false,
        manage: false,
        manageMembership: false,
      },
    },
  ],
  [],
  [],
];

export const kGroups = [
  {
    id: '9cf51b5d-e066-4ed8-940c-dc6da77f81a5',
    name: 'biggroup',
    path: '/biggroup',
    subGroupCount: 1,
    subGroups: [
      {
        id: 'eefa5b46-0509-41d8-b8b3-7ddae9c83632',
        name: 'subgroup',
        path: '/biggroup/subgroup',
        parentId: '9cf51b5d-e066-4ed8-940c-dc6da77f81a5',
        subGroupCount: 0,
        subGroups: [],
        access: {
          view: true,
          viewMembers: true,
          manageMembers: false,
          manage: false,
          manageMembership: false,
        },
        members: [],
        parent: 'biggroup',
      },
    ],
    access: {
      view: true,
      viewMembers: true,
      manageMembers: false,
      manage: false,
      manageMembership: false,
    },
    members: ['jamesdoe'],
  },
  {
    id: 'eefa5b46-0509-41d8-b8b3-7ddae9c83632',
    name: 'subgroup',
    path: '/biggroup/subgroup',
    parentId: '9cf51b5d-e066-4ed8-940c-dc6da77f81a5',
    subGroupCount: 0,
    subGroups: [],
    access: {
      view: true,
      viewMembers: true,
      manageMembers: false,
      manage: false,
      manageMembership: false,
    },
    members: [],
    parent: 'biggroup',
  },
  {
    id: '557501bd-8188-41c0-a2d5-43ff3d5b0258',
    name: 'emptygroup',
    path: '/emptygroup',
    subGroupCount: 0,
    subGroups: [],
    access: {
      view: true,
      viewMembers: true,
      manageMembers: false,
      manage: false,
      manageMembership: false,
    },
    members: [],
  },
];
