name: Test and build

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16

      - name: Install dependencies
        # --frozen-lockfile: doesn't generate a yarn.lock file, fails if an update is needed.
        run: yarn install --frozen-lockfile

      - name: Linter
        run: yarn lint:all

      - name: Prettier
        run: yarn prettier:check

      - name: Unit tests
        run: yarn test:all

      - name: Typescript test
        run: yarn tsc

      - name: Build code
        run: yarn build:all
